#!/usr/bin/env bash

set -eu -o pipefail

while [[ ! -e .git ]] && [[ "$(pwd)" != "/" ]]
do
    cd ..
done
PROJ_DIR="$( pwd )"

git init "${PROJ_DIR}/tmp/template-repo"
cd "${PROJ_DIR}/tmp/template-repo"
"${PROJ_DIR}/update/add/.devcontainer/scripts/update"
